class g():
  #----- COMM ADDRESSES ------#
  RESET_COMM_ADDRESS = 1    
  I2C_COMM_ADDRESS = 2   
  ACC_RAW_COMM_ADDRESS = 3
  ACC_OFFSET_COMM_ADDRESS = 4
  GYR_RAW_COMM_ADDRESS = 5
  GYR_OFFSET_COMM_ADDRESS = 6
  MAG_RAW_COMM_ADDRESS = 7
  MAG_CAL_COMM_ADDRESS = 8
  B_VECT_COMM_ADDRESS = 9
  A_MAT_0_COMM_ADDRESS = 10
  A_MAT_1_COMM_ADDRESS = 11
  A_MAT_2_COMM_ADDRESS = 12
  QUAT_COMM_ADDRESS = 13
  RPY_VAR_COMM_ADDRESS = 14
  GYR_VAR_COMM_ADDRESS = 15
  ACC_VAR_COMM_ADDRESS = 16
  GAIN_COMM_ADDRESS = 31
  ACC_CAL_COMM_ADDRESS = 32
  GYR_CAL_COMM_ADDRESS = 33
  RPY_COMM_ADDRESS = 34
  #--------------------------#
  
  app = None
  serClient = None
  port = "None"

  i2cAddress = None
  filterGain = None